main.cpp with file reading, 2 input test files
SimulationEverywhere-Models/Cadmium-SEIRD pull request #1
Opened 2020-06-10 17:22 UTC by saif9817

The first requested change to add file reading for the input, added an extra portion to default to a certain filename if no name is provided, have provided 2 test input files with a single change in the 2nd input, there are print statements commented out that were used for testing the functionality of the default and provided filename feature

2020-06-11 13:37 UTC, cruizm requested changes

2020-06-11 13:37 UTC, cruizm commented on top_model/top_model/main.cpp
> +	if(inputReader.is_open()){
Hello Saif,
This is good. Can you please modify it in such a way that in the name of the file we have the name of the input parameter, so everything is less error-prone?
Example:
mortality = 10.5
infectivity period = 15
...

2020-06-11 18:49 UTC, saif9817 commented
I have added the functionality to parse through tags, choosing to leave it in the exact order, I have added the assert to mortality only for testing, if you run the program with data.txt (which has an empty mortality field) it aborts the program but the message is not showing for me

2020-06-11 20:11 UTC, saif9817 commented
I have fixed the earlier issue, it is now providing specific errors

2020-06-12 13:47 UTC, saif9817 commented
Hi Cristina, please find the newly added comments for the code as well as a readme for the user input section and a template for users, please let me know if you need me to make any other changes

2020-06-15 13:15 UTC, cruizm approved these changes

2020-06-15 13:48 UTC, merged